use customer_analysis

#Q1. What is the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount)
FROM customer_shopping
group by gender ;


#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount
FROM customer_shopping
where discount_applied = 'Yes' and
purchase_amount >= (select AVG(purchase_amount) from customer_shopping) ;

#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(AVG(review_rating),2)
from customer_shopping
group by item_purchased
order by AVG(review_rating) desc
limit 5;

#Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount),2)
from customer_shopping
where shipping_type in ('Standard' , 'Express')
group by shipping_type;


#Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,count(customer_id) as count,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customer_shopping
group by subscription_status
order by avg_spend,total_revenue desc;

#Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment
WITH customer_type AS (
    SELECT customer_id,previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'NEW'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
            ELSE 'LOYAL'
        END AS customer_segment
    FROM customer_shopping
)
SELECT customer_segment,COUNT(customer_id) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

#Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id)
from customer_shopping
where previous_purchases > 5
group by subscription_status ;


# What is the revenue contribution of each age group? # age group column is not created... 
select age,sum(purchase_amount) as total_revenue
from customer_shopping
group by age
order by total_revenue;

















































































